package rrrr;

public enum MessageType {
    NO_DATA_WATER_LEVEL_SENSOR,
    NO_DATA_POO,
    NO_DATA_AHOV_POO,
    NO_DATA_AHOV_QUANTITY_POO,
    NO_DATA_BLAST_POO,
    NO_DATA_BLAST_QUANTITY_POO,
    NO_DATA_FUEL_POO,
    NO_DATA_FUEL_QUANTITY_POO,
    NO_DATA_FUEL_STORAGE_POO,
    NO_DATA_INCIDENT_COORDINATES,
    NO_DATA_FORECAST,
    NO_DATA_WRONG_FORECAST_TYPE,
    NO_DATA_FORECAST_OFF,
    NO_DATA_CHEMISTRY_ATMOSPHERE,
    NO_DATA_FIRE_FOREST;
}
